### ISSUE TITLE
Сan't compile VeraCrypt

### ISSUE THREAD

**Issue by Alash07** [veracrypt/VeraCrypt#1398]
Hello everyone. I can't compile VeraCrypt on Visual Studio 2022 from the source code you provided here https://github.com/veracrypt/VeraCrypt. I did everything as per the instructions, I gave the paths to the specified folders. But there are many errors of this nature:
1. Error C2079 "extensionPointDisablePolicy" uses an undefined structure struct "_PROCESS_MITIGATION_EXTENSION_POINT_DISABLE_POLICY" ExpandVolume C:\Vera\VeraCrypt-master\src\Common\Dlgcode.c 14479
2. Error C2011 _PROCESS_MITIGATION_POLICY: redefinition of type "enum" Format C:\Vera\VeraCrypt-master\src\Common\Dlgcode.c 14448
3. Error C2079 "aslrPolicy" uses an undefined structure struct "_PROCESS_MITIGATION_ASLR_POLICY" Format C:\Vera\VeraCrypt-master\src\Common\Dlgcode.c 14477
etc.
maybe I didn't specify additional paths?

**Comment by idrassi** [comment]
Thank you for the report

The issue is caused by Windows 10 SDK headers  conflicting with internal definitions. To fix this, we need to set minimun target version as Windows 8 for newer Visual Studui versions.

I have pushed the commit https://github.com/veracrypt/VeraCrypt/commit/c167799506f737b8d34133c824703291da797315 that fixes this issue\,

Feel free to reopen if the issue persists.

**Comment by Alash07** [comment]
Hello friend, you know I'm still new to this demo, maybe I've already had problems with such questions, can you help me with the solution assembly error?
![123](https://github.com/user-attachments/assets/59a798af-9306-4b4f-b37f-7273955203df)
Maybe I missed something? I tried to compile and recompile on different configurations with platforms, but in the end I got this error? Or maybe I should have chosen the SLN project that is 2019?
![1223](https://github.com/user-attachments/assets/c42659cf-101d-4544-b725-2b99de24cec7)

**Comment by idrassi** [comment]
Yes, you should use 2019 sln when using VS2022.
Also, you need to have "C++ ATL" component installed in Visual studio: run Visual Studio Install, click Modify and then go to "Individual Components" to select C++ ATL as shown below (screenshot is for VS2019 but it should be similar with VS2022):

![image](https://github.com/user-attachments/assets/dd06e495-aef0-4dfa-8d76-34fad9943837)

**Comment by Alash07** [comment]
I did everything as you said, but still get errors. I don't know what I did before, but it worked once, and now it doesn't work again and these are the errors. 
![1213](https://github.com/user-attachments/assets/e0505b96-65c9-4e34-94f1-e4c53d4b46d2)
First I set the solution configuration to All, and the platform to Win32, the same errors come out, then I set x64 and click rebuild the solution. But still the same errors come out.
Do you have a telegram channel? or telegram? Can you post a screen video of how you build this solution?

**Comment by Alash07** [comment]
Hello dude! I finally built a solution! But when opening the .exe file, I got this error))
![1223](https://github.com/user-attachments/assets/ce075b62-72e1-4500-983e-c73c33b77c30)
![Безымянный](https://github.com/user-attachments/assets/849dc2be-438c-482e-8078-ebc9844af52a)
Please help me what's the problem?
The source files are all from your source

**Comment by idrassi** [comment]
This error is triggered because the code in release mode checks that executables are signed with official IDRIX code signing certificate.

There are two simple ways to solve this:
- Build in Debug mode
- or Modify the function VerifyModuleSignature to make it always return TRUE (for example you can comment the if check at line 864 so that it always returns true at ligne 865.

**Comment by Alash07** [comment]
Hi friend. I did everything according to your recommendations, but alas, nothing worked for me. Did you do it yourself on Windows 10? If so, can you share your source code. On GitHub, it doesn't want to go in any direction.
 
 
С уважением,
Төлеби Тымбай
+7 707 303 61 93
