### ISSUE TITLE
veracrypt-(console)-1.24-Hotfix1-Debian errors

### ISSUE THREAD

**Issue by githuborer** [veracrypt/VeraCrypt#531]
> > 
> Die folgenden NEUEN Pakete werden installiert:
>   libwxbase3.0-0v5 libwxgtk3.0-0v5
> 0 aktualisiert, 2 neu installiert, 0 zu entfernen und 2 nicht aktualisiert.
> 1 nicht vollständig installiert oder entfernt.
> Es müssen 5.566 kB an Archiven heruntergeladen werden........
> 
> Entpacken von veracrypt-console (1.24.7-1) über (1.24.7-1) ...
> veracrypt-console (1.24.7-1) wird eingerichtet ...
> root@.../veracrypt-updates# veracrypt --version
> 19:34:08: **Error: Unable to initialize GTK+, is DISPLAY set properly?**
> 
> dpkg --status veracrypt-console
> Package: veracrypt-console
> Status: install ok installed
> Priority: optional
> Section: libs
> Installed-Size: 5186
> Maintainer: VeraCrypt Team <veracrypt@idrix.fr>
> Architecture: amd64
> Version: 1.24.7-1
> Depends: libwxgtk3.0-0v5, libfuse2, dmsetup
> Conflicts: veracrypt
> Description: Disk encryption with strong security based on TrueCrypt.
> 
> dpkg --purge veracrypt-console
> (Lese Datenbank ... 256413 Dateien und Verzeichnisse sind derzeit installiert.)
> Entfernen von veracrypt-console (1.24.7-1) ...
> 
> dpkg -i veracrypt-1.24-Hotfix1-Debian-9-amd64.deb
> Vormals nicht ausgewähltes Paket veracrypt wird gewählt.
> (Lese Datenbank ... 256228 Dateien und Verzeichnisse sind derzeit installiert.)
> Vorbereitung zum Entpacken von veracrypt-1.24-Hotfix1-Debian-9-amd64.deb ...
> Entpacken von veracrypt (1.24.7-1) ...
> veracrypt (1.24.7-1) wird eingerichtet ...
> Trigger für gnome-menus (3.13.3-9) werden verarbeitet ...
> Trigger für desktop-file-utils (0.23-1) werden verarbeitet ...
> Trigger für mime-support (3.60) werden verarbeitet ...
> 
> root:~$ veracrypt --version
> VeraCrypt 1.24-Hotfix1
> 
> (process:21662): GLib-GObject-CRITICAL **: g_type_class_unref: assertion 'g_class != NULL' failed

With veracrypt-console I get Unable to initialize GTK+, is DISPLAY set properly? error and can not use it. With veracrypt gui I can mount and use everything but at the end get always
GLib-GObject-CRITICAL **: g_type_class_unref: assertion 'g_class != NULL' failed messages

**Comment by idrassi** [comment]
This has been answered here: https://sourceforge.net/p/veracrypt/discussion/technical/thread/6b601c6949/?limit=25

Here is a quote:

> This might happen when using the console version of VeraCrypt over SSH without X11 Forwarding, which is your case.
> This is due to the fact that VeraCrypt-Console links against wxWidgets-GUI library (which links against GTK) because it makes use of wxApp.
> One way to fix this is by setting the environment variable DISPLAY like the following prior to running VeraCrypt-Console :
> `export DISPLAY=:0.0`

**Comment by githuborer** [comment]
I tried this variable. Its not working

**Comment by alt3r-3go** [comment]
@githuborer, does anything change when you set that variable, or all the error massages and output are identical?

**Comment by githuborer** [comment]
All the error massages and output were identical. I set the var in a putty session, not as an env variable

**Comment by alt3r-3go** [comment]
I see. Could you please then describe the steps you perform + your environment in more detail?

**Comment by idrassi** [comment]
@alt3r-3go I was able to reproduce the issue on a headless server by connecting to it using SSH with Putty. Indeed, setting `DISPLAY` environment variable doesn’t work but there is a workaround.

@githuborer You can workaround this issue by installing the standard veracrypt package instead of veracrypt-console one and then using `—text` switch when running VeraCrypt commands. I tested it and it works this way.

Now we need to understand why the standard package of VeraCrypt works better on headless servers using `--text` switch thank the console dedicated package, because clearly this is not the expected behavior.

**Comment by idrassi** [comment]
I have been able to fix this issue (cf commit https://github.com/veracrypt/VeraCrypt/commit/737e1f126b8826ed02418266e590e195aebdd7c0). In console mode, we didn't call `wxAppBase::Initialize` and this was causing a side effect in wxWidgets internals.

I'm attaching a zip containing the Debian 9 .deb package containing this fix alongside its PGP signature using the official VeraCrypt PGP key. 
Can you please confirm that it also fixes the issue on your side?
Thank you.

[veracrypt-1.24-Hotfix2-Preview2-Debian-9.9-amd64.zip](https://github.com/veracrypt/VeraCrypt/files/3856324/veracrypt-1.24-Hotfix2-Preview2-Debian-9.9-amd64.zip)

**Comment by githuborer** [comment]
@idrassi Thank you for investigating this issue. The standard veracrypt package already working for me too without --text flag. I wrote in first post:

it just give me this error message after any command:
```
root:~$ veracrypt --version
VeraCrypt 1.24-Hotfix1

(process:21662): GLib-GObject-CRITICAL **: g_type_class_unref: assertion 'g_class != NULL' failed
```
Preparing to unpack .../veracrypt-1.24-Hotfix2-Preview2-Debian-9.9-amd64.deb ...
Unpacking veracrypt (1.24.8-2) ...
Setting up veracrypt (1.24.8-2) ...
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...

Now I can mount my HDDs with veracrypt-1.24-Hotfix2 too but get this message after any command too:
(process:xxxxx): GLib-GObject-CRITICAL **: g_type_class_unref: assertion 'g_class != NULL' failed

> dpkg --status veracrypt-console
dpkg-query: package 'veracrypt-console' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
It seems that your package is not the veracrypt-console package

**Comment by idrassi** [comment]
@githuborer Indeed, I uploaded the wrong package! Sorry for this. I'm attaching this time the correct console package and I have fixed the link in my previous post. 
Thank you for your help/

[veracrypt-console-1.24-Hotfix2-Preview2-Debian-9.9-amd64.zip](https://github.com/veracrypt/VeraCrypt/files/3857569/veracrypt-console-1.24-Hotfix2-Preview2-Debian-9.9-amd64.zip)

**Comment by githuborer** [comment]
Okay installed it. Drives were mounted successfully but still this message at any command :
> dpkg --status veracrypt-console
Package: veracrypt-console
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 5190
Maintainer: VeraCrypt Team <veracrypt@idrix.fr>
Architecture: amd64
Version: 1.24.8-2
Depends: libwxgtk3.0-0v5, libfuse2, dmsetup, sudo
Conflicts: veracrypt
Description: Disk encryption with strong security based on TrueCrypt.
veracrypt --version

**(process:6078): GLib-GObject-CRITICAL **: g_type_class_unref: assertion 'g_class != NULL' failed**
VeraCrypt 1.24-Hotfix2-Preview2

**Comment by idrassi** [comment]
@githuborer Thank you for the confirmation  of the fix.

Concerning the assertion message displayed, it is caused by a issue in wxWidgets that was fixed in wxWidgets version 3.0.4 but Debian 9 ships with the older 3.0.2 version of wxWidgets.
You can install the same package on Debian 10 and this assertion message will not be displayed.

**Comment by githuborer** [comment]
Alright. Thanks for info. I close this

**Comment by ClearPathDigital** [comment]
I have the same issue on Debian 10 Buster.

I tried the console only version and got the same issue as OP.  So I installed the GUI version even though I don't have a Desktop installed.  But I still have the "assertion" problem after upgrading to Debian 10, freshly installed 9, upgraded to 10.

More info:

```
$ veracrypt --text
Usage: veracrypt [--auto-mount <str>] [--backup-headers] [--background-task] [-C] [-c] [--create-keyfile] [--delete-token-keyfiles] [-d] [--display-password] [-
-encryption <str>] [--explore] [--export-token-keyfile] [--filesystem <str>] [-f] [--fs-options <str>] [--hash <str>] [-h] [--import-token-keyfiles] [-k <str>]
[-l] [--list-token-keyfiles] [--load-preferences] [--mount] [-m <str>] [--new-hash <str>] [--new-keyfiles <str>] [--new-password <str>] [--new-pim <str>] [--non
-interactive] [--stdin] [-p <str>] [--pim <str>] [--protect-hidden <str>] [--protection-hash <str>] [--protection-keyfiles <str>] [--protection-password <str>]
[--protection-pim <str>] [--random-source <str>] [--restore-headers] [--save-preferences] [--quick] [--size <str>] [--slot <str>] [-tc] [--test] [-t] [--token-l
ib <str>] [--token-pin <str>] [-v] [--version] [--volume-properties] [--volume-type <str>] [--no-size-check] [Volume path] [Mount point]
  --auto-mount=<str>            Auto mount device-hosted/favorite volumes
  --backup-headers              Backup volume headers
  --background-task             Start Background Task
  -C, --change                  Change password or keyfiles
  -c, --create                  Create new volume
  --create-keyfile              Create new keyfile
  --delete-token-keyfiles       Delete security token keyfiles
  -d, --dismount                Dismount volume
  --display-password            Display password while typing
  --encryption=<str>            Encryption algorithm
  --explore                     Open explorer window for mounted volume
  --export-token-keyfile        Export keyfile from security token
  --filesystem=<str>            Filesystem type
  -f, --force                   Force mount/dismount/overwrite
  --fs-options=<str>            Filesystem mount options
  --hash=<str>                  Hash algorithm
  -h, --help                    Display detailed command line help
  --import-token-keyfiles       Import keyfiles to security token
  -k, --keyfiles=<str>          Keyfiles
  -l, --list                    List mounted volumes
  --list-token-keyfiles         List security token keyfiles
  --load-preferences            Load user preferences
  --mount                       Mount volume interactively
  -m, --mount-options=<str>     VeraCrypt volume mount options
  --new-hash=<str>              New hash algorithm
  --new-keyfiles=<str>          New keyfiles
  --new-password=<str>          New password
  --new-pim=<str>               New PIM
  --non-interactive             Do not interact with user
  --stdin                       Read password from standard input
  -p, --password=<str>          Password
  --pim=<str>                   PIM
  --protect-hidden=<str>        Protect hidden volume
  --protection-hash=<str>       Hash algorithm for protected hidden volume
  --protection-keyfiles=<str>   Keyfiles for protected hidden volume
  --protection-password=<str>   Password for protected hidden volume
  --protection-pim=<str>        PIM for protected hidden volume
  --random-source=<str>         Use file as source of random data
  --restore-headers             Restore volume headers
  --save-preferences            Save user preferences
  --quick                       Enable quick format
  --size=<str>                  Size in bytes
  --slot=<str>                  Volume slot number
  -tc, --truecrypt              Enable TrueCrypt mode. Should be put first to avoid issues.
  --test                        Test internal algorithms
  -t, --text                    Use text user interface
  --token-lib=<str>             Security token library
  --token-pin=<str>             Security token PIN
  -v, --verbose                 Enable verbose output
  --version                     Display version information
  --volume-properties           Display volume properties
  --volume-type=<str>           Volume type
  --no-size-check               Disable check of container size against disk free space.

(process:4531): GLib-GObject-WARNING **: 17:27:26.783: invalid (NULL) pointer instance

(process:4531): GLib-GObject-CRITICAL **: 17:27:26.783: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:4531): GLib-GObject-WARNING **: 17:27:26.783: invalid (NULL) pointer instance

(process:4531): GLib-GObject-CRITICAL **: 17:27:26.783: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

```
$ apt list --installed | grep -i wx

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libwxbase3.0-0v5/stable,now 3.0.4+dfsg-8 amd64 [installed,automatic]
libwxgtk3.0-gtk3-0v5/stable,now 3.0.4+dfsg-8 amd64 [installed,automatic]
```

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by idrassi** [comment]
@ClearPathDigital which issue do you still have? Did you use the .deb package attached above? You didn’t post VeraCrypt version so I don’t know if you used the above .deb.

Concerning the GTK assertion messages, these are different from before. They are harmless but we need to investigate them although I’m not sure if we can do anything about them since our code used wxWidgets not GTK. My hypothesis is that wxWidgets 3.0.4 has some issues with GTK3 compared to GTK2. Probably wxWidgets forums has reports for similar assertion messages.

**Comment by JakeSFR** [comment]
This commit https://github.com/veracrypt/VeraCrypt/commit/737e1f126b8826ed02418266e590e195aebdd7c0 breaks building VC for me using:

```
make NOGUI=1 WXSTATIC=1 WX_ROOT=/path/to/wxWidgets-3.0.4 wxbuild
make NOGUI=1 WXSTATIC=1
```

```
Compiling Application.cpp
In file included from Application.cpp:21:0:
TextUserInterface.h: In member function 'virtual bool VeraCrypt::TextUserInterface::Initialize(int&, wxChar**)':
TextUserInterface.h:50:63: error: 'wxAppBase' has not been declared
   virtual bool Initialize (int &argc, wxChar **argv) { return wxAppBase::Initia
                                                               ^
```
Can anyone confirm?

**Comment by ClearPathDigital** [comment]
@idrassi, I originall was not able to run veracrypt, and got the `Unable to initialize GTK+, is DISPLAY set properly?` error.  I upgraded to Debian 10, and installed the full version of the package instead of the console version.  I now get the assertion messages.  But those seem to be harmless for now.  So for now, my problem has been solved, but I would prefer to run the console version, and error-free.

**Comment by alt3r-3go** [comment]
@JakeSFR, yes, I observe the same, just checked (but haven't investigated what's the reason):

```shell
# wxWidgets build fine
$ make NOGUI=1 WXSTATIC=1 VERBOSE=1 WX_ROOT=/home/user/dev/vc/wx-src/ WITHGTK3=1 wxbuild
# VC itself fails in the way you posted
$ make NOGUI=1 WXSTATIC=1 VERBOSE=1
```

**Comment by gktrk** [comment]
> This commit [737e1f1](https://github.com/veracrypt/VeraCrypt/commit/737e1f126b8826ed02418266e590e195aebdd7c0) breaks building VC for me using:
> 
> ```
> make NOGUI=1 WXSTATIC=1 WX_ROOT=/path/to/wxWidgets-3.0.4 wxbuild
> make NOGUI=1 WXSTATIC=1
> ```
> 
> ```
> Compiling Application.cpp
> In file included from Application.cpp:21:0:
> TextUserInterface.h: In member function 'virtual bool VeraCrypt::TextUserInterface::Initialize(int&, wxChar**)':
> TextUserInterface.h:50:63: error: 'wxAppBase' has not been declared
>    virtual bool Initialize (int &argc, wxChar **argv) { return wxAppBase::Initia
>                                                                ^
> ```
> 
> Can anyone confirm?

Can you try passing `-DwxUSE_GUI=0` in CFLAGS when compiling VC? I'm guessing it's related to https://github.com/gentoo/gentoo/commit/ac3f1a90286538ec943337d34552553205aa3d05.

**Comment by gktrk** [comment]
> > This commit [737e1f1](https://github.com/veracrypt/VeraCrypt/commit/737e1f126b8826ed02418266e590e195aebdd7c0) breaks building VC for me using:
> > ```
> > make NOGUI=1 WXSTATIC=1 WX_ROOT=/path/to/wxWidgets-3.0.4 wxbuild
> > make NOGUI=1 WXSTATIC=1
> > ```
> > 
> > 
> > ```
> > Compiling Application.cpp
> > In file included from Application.cpp:21:0:
> > TextUserInterface.h: In member function 'virtual bool VeraCrypt::TextUserInterface::Initialize(int&, wxChar**)':
> > TextUserInterface.h:50:63: error: 'wxAppBase' has not been declared
> >    virtual bool Initialize (int &argc, wxChar **argv) { return wxAppBase::Initia
> >                                                                ^
> > ```
> > 
> > 
> > Can anyone confirm?
> 
> Can you try passing `-DwxUSE_GUI=0` in CFLAGS when compiling VC? I'm guessing it's related to [gentoo/gentoo@ac3f1a9](https://github.com/gentoo/gentoo/commit/ac3f1a90286538ec943337d34552553205aa3d05).

Scratch that, it doesn't help. The build still fails with:

```
In file included from Application.cpp:21:
TextUserInterface.h: In member function ‘virtual bool VeraCrypt::TextUserInterface::Initialize(int&, wxChar**)’:
TextUserInterface.h:50:63: error: ‘wxAppBase’ has not been declared
   50 |   virtual bool Initialize (int &argc, wxChar **argv) { return wxAppBase::Initialize(argc, argv); }
```

**Comment by gktrk** [comment]
@JakeSFR @alt3r-3go Can you try this branch please? https://github.com/gktrk/VeraCrypt/tree/wxwidgets-headless-fix

**Comment by JakeSFR** [comment]
@alt3r-3go, thanks for confirmation.

> @JakeSFR @alt3r-3go Can you try this branch please? https://github.com/gktrk/VeraCrypt/tree/wxwidgets-headless-fix

@gktrk, yeah, works for me, thanks!

**Comment by idrassi** [comment]
@JakeSFR Thank you for taking the time to fix this issue for good. Clearly my "fix" was not the real one. Can you please send a PR to integrate your modifications?

**Comment by gktrk** [comment]
@idrassi give it a shot: https://github.com/veracrypt/VeraCrypt/pull/570

**Comment by inthreedee** [comment]
@idrassi Have any of the changes discussed here affected package dependencies?  I run Veracrypt on a machine with Ubuntu Server 18.04 (console only, no desktop environment, no xorg) and 1.24 Hotfix 2 will not run for me.  When trying to run it, I get this error:
```
veracrypt: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```
Obviously that library is not installed because Ubuntu Server does not come with a desktop of any kind.  Veracrypt has always worked fine for me up to and including v1.24 Hotfix 1.

Will the PR from @gktrk fix this or should I make a separate ticket?

---

For background, I install Veracrypt using the Generic Installer because even the console version of the .deb file tries to install a bunch of xorg dependencies which are completely unnecessary for a consle-only server.

**Comment by idrassi** [comment]
@inthreedee Yes, this PR fixes the issue you have with the generic installer.

As a way to confirm this, I have created an installer for 1.24-Update3 based on @gktrk PR which is included in the zip below alongside its PGP signature. The output of `ldd` for console-only binary shows that there are no more dependencies to GTK:
```
$ ldd /usr/bin/veracrypt
	linux-gate.so.1 =>  (0x008d4000)
	libfuse.so.2 => /lib/libfuse.so.2 (0x00bb5000)
	librt.so.1 => /lib/librt.so.1 (0x00aed000)
	libdl.so.2 => /lib/libdl.so.2 (0x007cb000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0011d000)
	libm.so.6 => /lib/libm.so.6 (0x00de0000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x0020a000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00228000)
	libc.so.6 => /lib/libc.so.6 (0x00243000)
	/lib/ld-linux.so.2 (0x800ee000)
```
Can you confirm that it is working now as expected?

I will also look into the .deb packaging to see if it is possible to avoid pulling xorg dependencies for console-only package.

[veracrypt-1.24-Update3-setup.zip](https://github.com/veracrypt/VeraCrypt/files/3990794/veracrypt-1.24-Update3-setup.zip)

**Comment by inthreedee** [comment]
@idrassi Confirmed, that version does appear to be working.  I appreciate the quick response!

> I will also look into the .deb packaging to see if it is possible to avoid pulling xorg dependencies for console-only package.

Thank you, that would be wonderful; I would much prefer to use the .deb so my package manager is aware of the install.

**Comment by idrassi** [comment]
@inthreedee Thanks for the confirmation. Here is a .deb package that should work too. I changed the build system so that in case of console-only we link against our statically built wxWidgets instead of the system one and not console-only .deb package doesn't depend on GTK.

[veracrypt-console-1.24-Update3-Ubuntu-18.04-amd64.zip](https://github.com/veracrypt/VeraCrypt/files/3990885/veracrypt-console-1.24-Update3-Ubuntu-18.04-amd64.zip)
