### ISSUE TITLE
VeraCrypt hangs after partition encryption is 100%

### ISSUE THREAD

**Issue by jozic** [veracrypt/VeraCrypt#7]
I'm running VeraCrypt (VC) from linux mint 13 (ubuntu 12.04). 
When I try to create a partition volume using external hdd, VC shows progress and looks fine until it gets to 100%, after that both windows (Wizard and main window) become clean and nothing happens. I format 2.2TB partition as NTFS.
Didn't try command line yet

**Comment by idrassi** [comment]
Since the progress showed 100%, the VeraCrypt volume has been correctly created and the last step is calling the external program **mkfs.ntfs** in order to format the volume using NTFS.

How long did you wait? Actually, VeraCrypt calls mkfs.ntfs without the argument **--quick** which means that the NTFS formatting process will have to go through the hole 2.2 TB of data...

Anyway, your VeraCrypt partition volume is OK and you can mount it through VeraCrypt. After that, you perform the quick NTFS formatting by manually calling mkfs.ntfs --quick.

**Comment by idrassi** [comment]
I have just committed a modification that adds the switch "-f" to the mkfs.ntfs call in order to perform a quick format. The full format doesn't add any more security and I should have done this since the beginning. 
Thank you for reporting this.

**Comment by idrassi** [comment]
The link to the commit: https://github.com/veracrypt/VeraCrypt/commit/544c55debc4d1a99588de099ae2eede3d8f24585

**Comment by jozic** [comment]
thanks for the quick response!
encrypting took about 4 hours, than it hangs there for maybe 6-8 hours(still like that)
this is my second attempt actually and on first one i had to kill VC, after that I started it again and tried to mount the partition, but it gave me an error (don't remember the text) and wasn't able to mount it.
I will let you know how it goes now

**Comment by jozic** [comment]
also, is it possible to display the progress of mkfs.ntfs so that users are aware that something still happens?

**Comment by jozic** [comment]
finally it's completed! 
after your explanation i decided to wait a bit and it worked out, but anyway thanks for adding the flag. Some kind of progress would be nice to have though, or at least a warning-like message before users start to format partition.
Feel free to close the issue if you don't need it anymore

**Comment by idrassi** [comment]
Thanks for the update.

I'm not sure it is possible to monitor the progress of mkfs.ntfs or any of the other formatting programs used but I agree that a message or a progress dialog should be displayed while the formatting is in progress. I'll see how to add this.
